version: "3.9"
services:
  mongodb:
    container_name: mongo-clean-code-node-api
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: clean-code-node-api
    image: node:14
    working_dir: /usr/src/clean-code-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm run debug"
    volumes:
      - ./dist/:/usr/src/clean-code-node-api/dist
      - ./package.json:/usr/src/clean-code-node-api/package.json
    ports:
      - "3003:3003"
      - "9222:9222"
    links:
      - mongodb
