version: "3"
services:
  mongodb:
    container_name: mongo-clean-code-node-api
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: clean-code-node-api
    image: node:16
    working_dir: /usr/src/clean-code-node-api
    restart: always
    command: bash -c "npm install ---omit=dev --ignore-scripts && npm run debug"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/clean-node-api
    volumes:
      - ./dist/:/usr/src/clean-code-node-api/dist
      - ./package.json:/usr/src/clean-code-node-api/package.json
    ports:
      - "3003:3003"
      - "9222:9222"
    links:
      - mongodb
