name: Pull request

on:
  pull_request:
    branches:
      - 'production'
  push:
    branches:
      - 'production'

jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os}}-${{ hasFiles('**/package.json') }}

      - name: Install dependencies
        run: npm install
