name: Pull request

on:
  pull_request:
    branches:
      - 'production'
  push:
    branches:
      - 'production'

jobs:
  install:
    name: Installing packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: npm install

  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Run unit tests
        run: npm run test:unit

  e2e-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout dependencies
        uses: actions/checkout@v3

      - name: Restore dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json')}}

      - name: Run integration tests
        run: npm run test:integration
